### ISSUE TITLE
Create a wireframe of the Jokinator interface

### ISSUE THREAD

**Issue by amiedawn** [amiedawn/jokinator#1]
As a user, I want to see the dad joke of the day
When I click the next joke
Then a new joke is displayed
Have a pic of Nacho Libre posing with a big comment bubble and have the joke appear in the bubble like he is saying it

**Comment by joe-riley** [comment]
# Examples
* https://jokes.lol/random-jokes/
* https://www.cnn.com/interactive/2019/06/us/dad-joke-generator-trnd/
* https://dadjokegenerator.com/

**Comment by amiedawn** [comment]
Using Bulma, voting for jokes should be easy to set up an interface for. Here is an example, and it is easy if we want to do 2 side by side and maybe have face-offs in a given period of time where people vote and see who gets the most votes. To take it a step further, we could set up a bracket tournament and see what the best Dad joke is according to popular vote. That may be way too complicated...just a thought.
![voting pic](https://user-images.githubusercontent.com/69654746/98047932-0a762600-1dea-11eb-98aa-a3d8655fdbfc.png)

**Comment by amiedawn** [comment]
All right, I have looked into both Bulma and Materialize (and looked at others too, but it seemed like from conversation, they are what we were most interested in, and I still believe these are our best bets to choose from). Bulma is supposed to be more basic, easier to use, and its biggest strength is easy grids. However, its documentation is not very in-depth (one of the biggest complaints about it) and it is pretty difficult to customize supposedly. So, if we keep things pretty simple with our interface like things we have done thusfar in our projects, I think Bulma is the way to go. We should be able to do all of that kind of stuff with it. However, if we want to try any animation or things beyond the basics, I believe Materialize is the way to go.
