### ISSUE TITLE
The ability for the user to tweet via add Tweet button 

### ISSUE THREAD

**Issue by joe-riley** [amiedawn/jokinator#11]
https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview

**Comment by amiedawn** [comment]
I am working on Twitter features, likely that will go in a modal. Have created Twitter handle: @Jokinator3 and the linked email address is jokinator2020@outlook.com .

**Comment by amiedawn** [comment]
Branch for modal is named feature/#11-twitter-modal
