### ISSUE TITLE
Feature/#26-supply-joke

### ISSUE THREAD

**Issue by amiedawn** [amiedawn/jokinator#26]
- Create a modal that will show after user has been on site for 5-10 seconds that asks them if they would like to supply their own joke that could be shared on our Twitter page.

- Work through if it is better to have them enter the joke in the modal or just direct them to a different page to do that. Depends on if we want them to post directly to our Twitter page or have some sort of approval process.

**Comment by amiedawn** [comment]
HTML done.

**Comment by ghost** [comment]
I will be working this issue, this weekend.

**Comment by joe-riley** [comment]
Issue complete.
